id: P3BB0097B
initial_creation_type: ocr
source_metadata:
  volumes:
    8c8d47389a86496b937bd87bf39bab99:
      base_file: v014.txt
      image_group_id: I1PD95859
      title: དཔལ་ནག་པོ་ཆེན་པོའི་བསྟོད་པ་རྐང་པ་བརྒྱད་པ།
      total_pages: 1856
      volume_number: 14
